spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/ztf
    username: root
    password: zhang987789
#    seesion过期时间
  session:
    timeout: 86400

# 配置端口号和统一请求访问路径
server:
  servlet:
    context-path: /api
  port: 8080


# mybatis-plus自动转化驼峰式
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

